spring.application.name=MyCart
server.address=0.0.0.0
server.port=4242

# spring.datasource.url=jdbc:postgresql://SEU_HOST:5432/postgres
# spring.datasource.username=SEU_USUARIO
# spring.datasource.password=SUA_SENHA
# spring.datasource.driver-class-name=org.postgresql.Driver
