spring.application.name=MyCart
server.address=0.0.0.0
server.port=${PORT:4242}
spring.web.resources.add-mappings=true

spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=${SUPABASE_USERNAME}
spring.datasource.password=${SUPABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver